services:
  surat-franken:
    container_name: surat-franken
    restart: unless-stopped
    environment:
      - SERVER_NAME=:80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.env:/app/.env
    networks:
      - default
      - mysql-stack_mysql_network

networks:
  default: {}
  mysql-stack_mysql_network:
    external: true
